// All static Text shouwn on website
import { imgslider1, imgslider2, imgslider3, jacobimg, noahimg, aigeneratedaudio, aigenerateddeepfake, aigeneratedface, aigeneratedimage, aigeneratedtext } from "../assets";


// Navbar items
export const navLinks = [
    {
        id: "home",
        title: "Home"
    },
    {
        id: "project",
        title: "Project"
    },
    {
        id: "about us",
        title: "About us"
    },
    {
        id: "models",
        title: "Models"
    }
]


// Our project
export const project = [
    {
        id: "goal",
        bg: "",
        title: "Our Goal",
        text: "Our goal is to develop a comprehensive application that detects and distinguishes AI-generated content from human-generated content across various media formats, starting with images and expanding to video, text, and audio. Thus enabling anyone to recognize AI-generated content and combat the spread of misinformation in the digital world."
    },
    {
        id: "finalProduct",
        bg: "",
        text: "We want to develop an advanced and user-friendly application, that has the ability to easily detect AI-generated content. It will incorporate cutting-edge detection models and provide a seamless experience for users, enabling them to make informed decisions."
    },
    {
        id: "stepsInvolved",
        bg: "",
        text: "Specialized models are built for images, videos, text, and audio using machine learning and deep learning methods. Diverse datasets are acquired and utilized to train the detection models, enhancing their accuracy and reliability."
    }
]


// About Us
export const imageSlider = [
    {
        id: "img-1",
        source: imgslider1
    },
    {
        id: "img-2",
        source: imgslider2
    },
    {
        id: "img-3",
        source: imgslider3
    }
]

export const about = [
    {
        id: "noah",
        title: "Noah Brömme",
        content: "Hello! I have lived in NY for 9 years. I have found interest in technology and AI. I also play the piano and the guitar and I am amazed by the art of photography. With the rise of deepfakes and AI-generated content in our everyday lives, I found myself interested in these topics.",
        personimg: jacobimg
    },
    {
        id: "jacob",
        title: "Jacob Heldt",
        content: "Hello! After living in the Netherlands for 7 years, I now live in New York since 2 years and have developed passion for technology, creativity, and innovation. Machine Learning is a significant area of interest for me, and I am constantly striving to improve my understanding and expertise in this field. ",
        personimg: noahimg
    }
]


// Our Models
export const theModels = [
    {
        id: "imgDetection",
        title: "Image Detector",
        modelimg: aigeneratedimage,
        imgsubtitle: '"a renaissance painting of an elephant in a tuxedo" by bing image creator',
        content: 'A machine learning model that can detect AI generated images and can distinguish them from real images. Ranging from cars, houses, apples and all kinds of everyday objects'
    },
    {
        id: "faceDetection",
        title: 'AI Generated Face Detection',
        modelimg: aigeneratedface,
        imgsubtitle: '"A renaissance painting of an elephant in a tuxedo" by bing image creator',
        content: 'A machine learning model that can detect faces generated by AI and can distinguish them from real faces. This is useful for example when detecting fake profiles on social media platforms'
    },
    {
        id: "textDetection",
        title: 'Text Detector',
        modelimg: '',
        imgsubtitle: '"Text" by bing image creator',
        content: 'A machine learning model that detects AI generated text. These texts can for example be based on ChatGPT generations.'
    },
    {
        id: "audioDetection",
        title: 'Audio Detector',
        modelimg: aigeneratedaudio,
        imgsubtitle: '"Audio" by bing image creator',
        content: 'A machine learning model that can detect AI generated audio and music. This can range from voices to generated music.'
    },
    {
        id: "deepfakeDetection",
        title: 'Deepfake Detector',
        modelimg: aigenerateddeepfake,
        imgsubtitle: '"Video" by bing image creator',
        content: 'A machine learning model that can detect advanced deepfakes. This is the highest form of AI generated content detection.'
    }
]


