import React from 'react'
import styles from '../style'
import logo from '../assets/Logo.png'
import Button from './Button'
import herobg from '../assets/herobg.png'

const Hero = () => {
  return (
    <section id="home" className={`flex md:flex-row flex-col ${styles.paddingY} font-poppins`}>
      <div className={`flex-1 ${styles.flexStart} flex-col md:ml-36 md:mr-36 ml-8 mr-8 mt-10`}>

      <div className='relative w-full mb-12'>
      <h2 className='font-secondary text-3xl font-poppins mb-2 z-20 relative'>Advanced AI Detector</h2>      
      <h1 className='z-20 relative text-white text-9xl font-righteous mb-4'>SyntheticEye</h1>
      <p className='text-white font-light relative z-20'>Created by Noah Brömme and Jacob Heldt</p>
    </div>

    <img 
      src={`${herobg}`}
      alt="Descriptive alt text" 
      className="absolute z-10 right-36 md:-top-0 mt-28 opacity-60" 
      style={{ width: '470px', height: '350px' }} 
  />

        <Button text="Try it!" />

        {/* Quote */}
        <div className="flex flex-row items-center py-6 px-9 bg-quote-gradient rounded-md mt-16">
          <p>
            <span className='text-white font-light tracking-wide font-poppins'>"Artificial intelligence has the power to create astonishingly realistic and compelling content, but with that power comes the inherent danger of manipulation, misinformation, and the erosion of trust in what is real and genuine."<span className='text-gray-300 not-italic'>  - ChatGPT</span></span>
          </p>
          
        </div>
        
        <div className='flex flex-row flex-col items-center justify-center w-full rounded-md mt-12'>
          <span className='mb-0'><span className='secondary-gradient text-4xl font-bold'>90% </span><span className='text-white text-lg font-light'>of online content may be AI generated by 2026</span></span>
          <span className='text-gray-300 italic text-sm font-light'>Deep Fakes and the Infocalypse, Nina Schick</span>
        </div>

      </div>
    </section>
  )
}

export default Hero 